// Landing copy, English. ka.ts and ru.ts follow exactly this shape.

export const en = {
  meta: {
    title: "Loudpilot — AI marketing: content, video, ads and analytics",
    description: "Loudpilot writes, designs, films and schedules for your brand, follows your ads — then reads the results and tells you what to do next.",
  },
  nav: {
    features: "Features",
    integrations: "Integrations",
    resources: "Resources",
    pricing: "Pricing",
    login: "Log in",
    tryFree: "Try free",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    home: "Loudpilot home",
    language: "Language",
  },
  badges: { new: "New", soon: "Soon", comingSoon: "Coming soon" },
  menu: {
    integrationsNote: "Connectors roll out network by network — plan posts for any of them today.",
    partnerApi: "Partner API",
    requestNetwork: "Request a network",
    product: "Product",
    company: "Company",
    resources: {
      pricing: { label: "Pricing", body: "Plans, credits and the free trial" },
      api: { label: "Partner API", body: "Workspaces, credits and revenue share" },
      docs: { label: "API documentation", body: "Endpoints, connect links and webhooks" },
      partner: { label: "Become a partner", body: "Bring Loudpilot to your customers" },
      sales: { label: "Contact sales", body: "A demo for your team" },
      support: { label: "Support", body: "Questions about your account" },
    },
  },
  integrations: {
    Facebook: "Posts for your business pages.",
    Instagram: "Feed posts, Reels and Stories.",
    TikTok: "Short-form video with captions.",
    LinkedIn: "Profiles and company pages.",
    "X (Twitter)": "Posts and threads.",
    Threads: "Text-first updates.",
    "YouTube Shorts": "Vertical video.",
    Pinterest: "Pins for the right boards.",
    Bluesky: "The open social network.",
    Telegram: "Channels and groups.",
    WhatsApp: "Channel updates.",
    "Google Business": "Updates on your business profile.",
    Discord: "Server announcements.",
    Mastodon: "Any server on the fediverse.",
    WordPress: "Blog articles on your own site.",
    WooCommerce: "New products become posts.",
    "Meta Ads": "Campaign results and lead forms.",
    "Google Ads": "Search and display campaigns.",
  } as Record<string, string>,
  features: {
    publish: {
      title: "Planner",
      short: "Plan and publish every post on one calendar.",
      headline: "One calendar for everything you post",
      intro:
        "Write once, adapt per network and see the whole month at a glance. Drafts, scheduled posts, videos, campaigns and blog articles live side by side — and go out to Facebook and Instagram on time.",
      points: [
        { title: "Month and list views", body: "See the whole month, or work through a clean list of what is next." },
        { title: "Publishing to Facebook and Instagram", body: "Schedule or publish now: photos, carousels, videos and Reels." },
        { title: "Your time zone", body: "Every date is planned in your own zone, daylight-saving switches included." },
        { title: "Results on every post", body: "Reach, views, likes, comments and saves come back to the post." },
      ],
    },
    campaigns: {
      title: "Campaigns",
      short: "A run of social posts or a series of articles from one brief.",
      headline: "A whole campaign from one brief",
      intro:
        "Describe the goal, pick the dates and how often to post. Loudpilot writes every post in your brand voice and lays it out on the calendar — ready to review, rewrite or schedule.",
      points: [
        { title: "Social campaigns", body: "Up to 8 weeks, 1–7 posts a week, each with its own caption, hashtags and date." },
        { title: "Blog series", body: "An outline for every article first; write the full article only when you need it." },
        { title: "Not sure what to run?", body: "Loudpilot suggests audiences by location and product, asks what it needs to know and proposes ideas." },
        { title: "Your brand inside", body: "Voice, audience and what worked before come from your dossier — no prompt engineering." },
      ],
    },
    design: {
      title: "Design Studio",
      short: "The built-in editor behind every visual you post.",
      headline: "Design on-brand visuals in minutes",
      intro:
        "Start from a template sized for each network, drop in your colours and logo, and send it straight into a post. Edit AI images the same way. No designer queue, no file juggling.",
      points: [
        { title: "Templates per format", body: "Square, portrait, story and landscape — resize a design without starting over." },
        { title: "Text, shapes and images", body: "Layers, alignment, undo and autosave, right in the browser." },
        { title: "Edit any image", body: "Uploads and AI images open in the Studio and go back into the post." },
        { title: "Your colours by default", body: "The palette comes from your brand kit." },
      ],
    },
    video: {
      title: "Video Studio",
      short: "Reels and Stories from your photos, clips or AI.",
      headline: "Short videos that stop the scroll",
      intro:
        "Turn photos and clips into Reels and Stories with text, motion, voice-over, music and your logo at the end — or let AI write the script, voice it and generate the footage.",
      points: [
        { title: "Scenes, text and motion", body: "Photos zoom and pan, clips trim, text appears in your brand style." },
        { title: "AI script and voice-over", body: "A hook, one idea per scene and a clear call to action — read by a natural voice." },
        { title: "AI clips with Google Veo", body: "Describe a scene or animate your own photo. On paid plans." },
        { title: "Straight to Reels", body: "Render to MP4 and publish to Instagram Reels and Facebook." },
      ],
    },
    bio: {
      title: "Bio pages",
      short: "One link-in-bio page for every profile.",
      headline: "A link-in-bio page that looks like your brand",
      intro:
        "Put every link that matters behind a single address. Build the page in minutes, publish it on your own Loudpilot link and see which links people actually click.",
      points: [
        { title: "Links, headings and socials", body: "Arrange blocks in any order and style them with your colours." },
        { title: "Click tracking", body: "Views and clicks per link, without third-party trackers." },
        { title: "Your own address", body: "Pick a short, memorable slug for every profile." },
        { title: "Live preview", body: "See the phone view while you edit." },
      ],
    },
    inbox: {
      title: "Social Inbox",
      short: "Messenger and Instagram DMs in one place.",
      headline: "Every conversation in one inbox",
      intro: "Direct messages from your Facebook Pages and Instagram accounts in one list — with on-brand reply drafts so nobody waits.",
      points: [
        { title: "One list for all profiles", body: "Messenger and Instagram Direct, unread counts and search." },
        { title: "AI reply drafts", body: "Answers in your brand voice from what Loudpilot knows about your company; you send every reply." },
        { title: "Meta's 24-hour rule built in", body: "You see when a reply is still allowed before you type." },
        { title: "Comments next", body: "Comments and mentions are coming to the same list." },
      ],
    },
    workflows: {
      title: "Workflows",
      short: "Automate posting and replies visually.",
      headline: "Marketing that runs itself",
      intro:
        "Connect a trigger to an action: a new product on your site becomes a scheduled post, a new listing becomes a campaign, a new comment gets a drafted reply.",
      points: [
        { title: "Triggers", body: "New product, new lead, a date, or an event from a partner app." },
        { title: "AI steps", body: "Write a caption, generate a visual or pick the best time." },
        { title: "Actions", body: "Create a post, start a campaign or notify your team." },
      ],
    },
    api: {
      title: "Partner API",
      short: "Give every customer of your product a marketing module.",
      headline: "Loudpilot inside the product you already run",
      intro:
        "Connect your SaaS, CRM or marketplace once. Each of your companies, agents or sellers gets an isolated workspace with its own brand, content and credits — you keep your UI.",
      points: [
        { title: "Workspace per customer", body: "Created by your external id, fully isolated from every other customer." },
        { title: "Single or reseller mode", body: "One company, or many profiles under your platform." },
        { title: "Credits and revenue share", body: "Customers pay Loudpilot for credits; you earn a share of every purchase." },
        { title: "Hashed keys", body: "API keys are shown once and stored only as a hash." },
      ],
    },
    ads: {
      title: "Ads & analytics",
      short: "Ad results, goals and a weekly plan of what to do next.",
      headline: "Ads and results that explain themselves",
      intro:
        "Follow your Meta campaigns next to your posts: spend, leads, cost per result and reach for the last 12 months. Set goals, get alerts when something goes off track, and every Monday a review with recommendations.",
      points: [
        { title: "One dashboard", body: "Ads and organic posts in one place, with an AI summary in plain words." },
        { title: "Goals and alerts", body: "Cost per lead, reach or engagement targets — Loudpilot tells you when a number slips." },
        { title: "Weekly review", body: "What worked, what didn't, and ready-to-apply posts and goals for next week." },
        { title: "Strategy with forecasts", body: "Plans with budgets and expected results from your own ad history." },
      ],
    },
  } as Record<string, { title: string; short: string; headline: string; intro: string; points: { title: string; body: string }[] }>,
  hero: {
    badge: "AI video with Google Veo",
    title: "Content, video and ads. Run by AI.",
    sub: "Loudpilot writes, designs, films and publishes your posts, follows your ads — then reads the results and tells you exactly what to change.",
    start: "Start free",
    how: "See how it works",
    mock: {
      post: "Fresh out of the oven: our new pistachio croissant 🥐 First 50 get a free coffee this weekend.",
      when: "Instagram · Fri 18:30",
      scheduled: "Scheduled",
      aiWritten: "AI-written · on brand",
      campaign: "Weekend promo · Meta Ads",
      spend: "Spend",
      leads: "Leads",
      cpl: "CPL",
      recommendation: "Recommendation",
      recText: "Ad set “Women 25–34, Tbilisi” brings leads 31% cheaper. Move ₾20/day from “Broad” and refresh creative #2 — its CTR fell 3 days in a row.",
      apply: "Apply",
      details: "Details",
    },
  },
  strip: {
    title: "The best AI models for text, image and video — behind one simple workflow",
    items: ["Captions in English, Georgian and Russian", "Image generation", "AI video and voice-over", "Meta Ads analytics", "Daily performance sync", "Inbox with AI replies"],
  },
  brief: {
    eyebrow: "From idea to campaign",
    title: "One brief in. A month of content out.",
    points: [
      { title: "Posts that sound like you", body: "Give it one line. Get a finished caption, hashtags and a call to action in your brand voice." },
      { title: "Visuals and video in seconds", body: "Images, carousels and Reels generated in your colours and style — no designer queue." },
      { title: "It asks before it guesses", body: "Not sure who your audience is? Loudpilot proposes audiences by location and product and asks what it needs." },
    ],
    cta: "Try it free",
    calendar: {
      month: "October",
      auto: "Auto-filled · best times",
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      carousel: "Carousel",
      promo: "Ad · Promo",
      reel: "Reel",
      post: "Post",
      retarget: "Ad · Retarget",
      story: "Story",
      launch: "Ad · Launch",
    },
  },
  steps: {
    eyebrow: "How it works",
    title: "Four steps. No busywork.",
    sub: "Set up your brand once — every post, video and report after that is written, designed and measured for you.",
    items: [
      { title: "Connect your brand", body: "Add your website, social pages and ad accounts. Loudpilot learns your voice, colours and audience once." },
      { title: "Get your audit", body: "We read the last 12 months of posts and ads and show what works, what wastes money and when to post." },
      { title: "Approve the plan", body: "A month of posts and campaigns is drafted for you. Edit anything, or approve it all in one click." },
      { title: "Publish and improve", body: "Loudpilot publishes, syncs results daily, watches your goals and suggests the next move every week." },
    ],
  },
  suite: {
    eyebrow: "One suite",
    title: "Everything your marketing needs — in one place",
    sub: "Organic content, video and ad results share one brand, one calendar and one set of numbers.",
    items: [
      { title: "Ready-to-publish posts", body: "Caption, visual, hashtags and timing in one go — adapted to each network's format and limits." },
      { title: "AI photo & video", body: "Product shots, banners, Reels and AI clips from a prompt or your own photos." },
      { title: "Ad results", body: "Meta campaigns' spend, leads and cost per result next to your posts — with goals and alerts." },
      { title: "Analytics that explain themselves", body: "Reach, engagement, spend and cost per lead across every account — with plain-language insights and the next best action." },
      { title: "Brand kit and dossier", body: "Voice, colours, audience and what worked before — applied to everything the AI creates." },
      { title: "Inbox with AI replies", body: "Messenger and Instagram DMs in one list, with on-brand reply drafts." },
      { title: "Smart scheduling", body: "One calendar for every network, at the times your audience is actually online." },
    ],
    networks: "Plan for every major network — publish to Facebook and Instagram today",
  },
  partners: {
    eyebrow: "Platform & API",
    title: "Use it here — or inside the product you already run",
    sub: "Loudpilot is a platform first. Connect your SaaS, CRM or marketplace and give every one of your customers their own marketing module.",
    apiTitle: "Partner API",
    apiBody: "Each of your companies, agents or sellers gets an isolated workspace with its own brand, social accounts, campaigns and credits. You keep your UI — Loudpilot does the marketing.",
    apiPoints: ["Workspace per customer, fully isolated", "Revenue share on every credit purchase", "Webhooks for alerts and results"],
    mcpTitle: "Let your AI assistant drive",
    mcpBody: "Connect Claude, ChatGPT, Cursor or VS Code over MCP and ask in plain words: “Plan next month's posts and a lead campaign for the new collection.”",
    mcpQ: "How did last week's ads do?",
    mcpA: "₾412 spent, 81 leads at ₾5.09 — 18% cheaper than the week before. Video ads beat images 2:1. Want me to add two more video posts to next week's plan?",
    mcpLink: "Connect your assistant",
  },
  compare: {
    eyebrow: "Why Loudpilot",
    title: "Schedulers post. Ad managers report. Loudpilot does both — and tells you what's next.",
    sub: "It reads the results, so every next post and every next ₾ works harder.",
    capability: "Capability",
    schedulers: "Post schedulers",
    adsManagers: "Ads managers",
    rows: [
      "AI posts, images and video",
      "Ad results with goals and alerts",
      "Organic + ads in one place",
      "Weekly review with AI recommendations",
      "Inbox with AI reply drafts",
      "Georgian language & local currency",
      "White-label API for platforms",
    ],
    addOn: "Add-on",
    basic: "Basic",
    manual: "Manual",
    some: "Some",
  },
  agency: {
    eyebrow: "The real comparison",
    title: "The output of a marketing agency — for the price of a lunch a week.",
    sub: "Agencies charge thousands a month for posts, videos and reports. Loudpilot does the same work every day, from $29.",
    cta: "See plans & pricing",
  },
  pricing: {
    eyebrow: "Pricing",
    title: "Clear pricing. No surprises.",
    sub: "Pick the seats, companies and monthly content you need. Try any plan free for 7 days.",
    monthly: "Monthly",
    yearly: "Yearly (2 months free)",
    popular: "Most popular",
    perMonth: "/ month",
    billedYearly: "Billed yearly — ${total}",
    billedMonthly: "Billed monthly",
    startTrial: "Start free trial",
    included: "What's included",
    users: "Users",
    companies: "Companies",
    profiles: "Social & ad profiles",
    credits: "AI credits / month",
    monthHead: "Every month",
    posts: "AI-written posts",
    images: "AI images",
    videos: "AI videos with voice-over",
    articles: "Blog articles",
    strategies: "Strategy plans",
    flex: "Runs on {credits} AI credits — use them for any mix you like.",
    veo: "AI clips (Veo) / month",
    api: "API & webhooks",
    perks: ["Fresh allowance every month", "Add profiles and seats as you grow", "Change plan or cancel anytime"],
    moreTitle: "Need more than Agency?",
    moreBody: "Custom limits, white-label and revenue share for platforms that resell Loudpilot to their own customers.",
    talk: "Let's talk",
    vat: "All prices in USD and include 18% VAT.",
    rivals: {
      title: "Same team, compared",
      sub: "5 people and 20 social profiles, per month.",
      tool: "Tool",
      plan: "Plan",
      price: "Price / month",
      incl: "incl. VAT",
      ours: "In Loudpilot Team, at this price",
      oursItems: [
        "1,500 AI credits: posts, images, videos, strategy plans",
        "Meta ads results and boosting posts",
        "Google Analytics and Search Console next to your ads",
        "SEO and AI search checks",
        "Georgian, English and Russian",
      ],
      note: "Public list prices on the vendors' websites, October 2026, in USD. Annual billing where a monthly price isn't published; local taxes may apply.",
      basis: {
        buffer: "$10 × 20 channels",
        hootsuite: "$199 × 5 users, billed yearly",
        sprout: "$299 × 5 seats, billed yearly",
      },
    },
    blurbs: {
      Starter: "For founders and small brands running their own marketing.",
      Team: "For marketing teams handling a few brands and ad accounts.",
      Agency: "For agencies and partners serving many clients at once.",
    } as Record<string, string>,
  },
  get: {
    eyebrow: "Why teams switch",
    title: "What you actually get",
    sub: "Not another caption generator — a marketing team that never sleeps and always shows its numbers.",
    items: [
      { title: "It learns your brand once", body: "Describe your business one time. Every caption, image and video after that stays on voice and on style.", tag: "Brand kit and dossier" },
      { title: "Ad plans without an ads specialist", body: "Audiences, budgets and forecasts from your own results — then goals and alerts watch the campaigns for you.", tag: "Meta Ads" },
      { title: "Recommendations, not just charts", body: "Every Monday Loudpilot reviews the week and tells you what to stop, what to scale and what to post next.", tag: "Weekly review" },
      { title: "Months of calendar in minutes", body: "Turn one idea into a full campaign spread across weeks, at the hours your audience is online.", tag: "Auto-scheduled" },
    ],
    calendarTitle: "One calendar, every network",
    calendarBody: "Posts, videos and campaigns side by side, from one place.",
  },
  final: {
    title: "Give your brand a voice that never goes quiet",
    sub: "Connect your pages in a minute and get your first audit and content plan today.",
    start: "Start free",
    demo: "Book a demo",
    note: "No credit card · Cancel anytime",
  },
  footer: {
    tagline: "AI marketing: content, video, ads and analytics in one place.",
    features: "Features",
    product: "Product",
    company: "Company",
    legal: "Legal",
    howItWorks: "How it works",
    adsAnalytics: "Ads & analytics",
    apiDocs: "API documentation",
    pricing: "Pricing",
    contactSales: "Contact sales",
    support: "Support",
    login: "Log in",
    startFree: "Start free",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    deletion: "Data deletion",
    rights: "All rights reserved.",
  },
  featurePage: {
    earlyAccess: "Get early access",
    talk: "Talk to us",
    start: "Start free",
    docs: "Read the docs",
    pricing: "See pricing",
    more: "More in Loudpilot",
  },
};

export type Copy = typeof en;
